<a href="https://colab.research.google.com/github/saranyareddy77/MDS-LAB/blob/main/mds_week1%2Cipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#install numpy
pip install numpy

In [1]:
# Import the numpy library
import numpy as np
print(np.__version__)

2.0.2


In [124]:
#creating list
list=[100,2,3,4,5]

In [125]:
#check the type of list
type(list)

list

In [126]:
#creating arr with numpy
arr1=np.array(list)

In [127]:
#printing the array
print(arr1)

[100   2   3   4   5]


In [128]:
#type of numpy array
type(arr1)

numpy.ndarray

In [129]:
#dimension of array
arr1.ndim

1

In [130]:
#type of array
arr1.dtype

dtype('int64')

In [131]:
#only to print type of array
arr1.dtype.name

'int64'

In [132]:
#size of array
arr1.size

5

In [133]:
#shape of array
arr1.shape

(5,)

In [134]:
#number of bytes used
arr1.nbytes

40

In [145]:
#creating a tuple
tuple=(100,2,3,5)

In [146]:
#datatype of the tuple
type(tuple)

tuple

In [148]:
#creating single element tuple wongly
tuple1=(100)

In [149]:
#type of single eleemt in tuple
type(tuple1)

int

In [150]:
#single element tuple
tuple2=(100,)

In [151]:
#printing single element of tuple
tuple2

(100,)

In [153]:
#datatype of tuple
type(tuple2)

tuple

In [154]:
#using numpy creating tuple
arr2=np.array(tuple)

In [155]:
#printing the tuple
print(arr2)

[100   2   3   5]


In [156]:
#dimension of tuple numpy array
arr2.ndim

1

In [158]:
#shape of array
arr2.shape

(4,)

In [159]:
#size of the array
arr2.size

4

In [160]:
#dtpe of array
arr2.dtype.name

'int64'

In [165]:
#no of bytes of memory
arr2.nbytes

32

In [166]:
#two dimensional list
list1=[[100,2],[3,4]]

In [168]:
# creating a matrix
matrix=np.array(list1)

In [170]:
#pirnting the matrix
print(matrix)

[[100   2]
 [  3   4]]


In [231]:
#dimension of matrix
matrix.ndim

2

In [232]:
#shape of matrix
matrix.shape

(2, 2)

In [233]:
#size of matrix
matrix.size

4

In [174]:
#no of bytes of memory used
matrix.nbytes

32

In [175]:
#2d matrix to 1d
matrix.flatten()

array([100,   2,   3,   4])

In [176]:
#ravel function
matrix.ravel()

array([100,   2,   3,   4])

In [178]:
#creating array using numpy
arr4=np.array([100,2,3,4])

In [179]:
#printing the array
print(*arr4)

100 2 3 4


In [181]:
#2d array using numpy
arr5=np.array([[100,2],[3,4]])

In [182]:
#printing the array
print(arr5)

[[100   2]
 [  3   4]]


In [183]:
#creating 3row and 2 col array
arr6=np.matrix([[100,2],[3,4],[5,6]])

In [184]:
# Print the 3x2 matrix
print(arr6)

[[100   2]
 [  3   4]
 [  5   6]]


In [185]:
import numpy as np

# Create a 1D array with numbers from 1 to 100
arr_1_to_100 = np.arange(1, 101)

# Print the array
print(arr_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [186]:
# Create a 1D array with numbers from 1 to 99
arr7=np.arange(1,100)

In [187]:
# Print the array arr7
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [188]:
# Create an array with even numbers from 0 to 100
arr8=np.arange(0,101,2)

In [189]:
# Print the array arr8
print(arr8)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [190]:
# Create an array with even numbers up to 98 (excluding 100)
arr9=np.arange(100,step=2)

In [191]:
# Print the array arr9
print(arr9)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [192]:
matrix2=np.arange(100,110)

In [193]:
# Print the 1D array matrix2
print(matrix2)

[100 101 102 103 104 105 106 107 108 109]


In [198]:
matrix2=np.arange(100,110).reshape(2,5)

In [199]:
# Print the reshaped 2D array matrix2
print(matrix2)

[[100 101 102 103 104]
 [105 106 107 108 109]]


In [200]:
# Flatten the 2D array to 1D
matrix2.flatten()

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [201]:
# Create a 3x3 array of zeros (default float type)
a=np.zeros((3,3))

In [202]:
# Print the array 'a'
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [203]:
# Check the data type of array 'a'
a.dtype.name

'float64'

In [204]:
# Create a 3x3 array of zeros with integer data type
a=np.zeros((3,3),dtype='int')

In [205]:
# Print the integer array 'a'
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [206]:
# Create a 3x3 array of ones with integer data type
b=np.ones((3,3),dtype='int')

In [207]:
# Print the array 'b' (all ones)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [209]:
c=np.full((3,3),100)

In [210]:
# Print the array 'c' (all 100s)
print(c)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [211]:
d=np.full((10,10),100)

In [212]:
# Print the array 'd' (10x10 with 100s)
print(d)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [213]:
# Create a 3x3 identity matrix
e=np.eye(3)

In [214]:
# Print the identity matrix 'e'
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [215]:
f=np.linspace(100,105,5)

In [216]:
# Print the array 'f' (linearly spaced numbers)
print(f)

[100.   101.25 102.5  103.75 105.  ]


In [217]:
# Import random module
import random as random
# Create a 3x3 array with random float values
g=np.random.random((3,3))

In [218]:
# Print the random array 'g'
print(g)

[[0.92200218 0.62293324 0.13874117]
 [0.20725019 0.48752702 0.86269476]
 [0.6525295  0.12550189 0.06031927]]


In [219]:
arr10=np.arange(100,110)

In [220]:
# Print the array arr10
print(arr10)

[100 101 102 103 104 105 106 107 108 109]


In [221]:
# Modify the first element of arr10
arr10[0]=111


In [222]:
# Print the modified arr10
print(arr10)

[111 101 102 103 104 105 106 107 108 109]


In [223]:
# Attempt to assign a string to an integer array element (will raise ValueError)
arr10[2]='dsc'

ValueError: invalid literal for int() with base 10: 'dsc'

In [224]:
# Find the maximum value in arr10
arr10.max()

np.int64(111)

In [225]:
# Modify a slice of arr10
arr10[2:5]=[333,444,555]

In [226]:
# Print arr10 after slice modification
print(arr10)

[111 101 333 444 555 105 106 107 108 109]


In [227]:
# Find the minimum value in arr10
arr10.min()

np.int64(101)

In [228]:
# Calculate the mean of arr10
arr10.mean()

np.float64(207.9)

In [229]:
# Create a NumPy array of strings
string_array = np.array(['apple', 'banana', 'cherry', 'date'])
print("Original string array:", string_array)
print("Data type of string array:", string_array.dtype)


Original string array: ['apple' 'banana' 'cherry' 'date']
Data type of string array: <U6


In [230]:
# Accessing elements
print("First element:", string_array[0])
print("Slice of elements:", string_array[1:3])

# Element-wise string operations using np.char
# np.char provides a set of vectorized string operations.

# Convert to uppercase
uppercase_array = np.char.upper(string_array)
print("Uppercase array:", uppercase_array)

# Concatenate strings
concatenated_string = np.char.add(string_array, '_fruit')
print("Concatenated array:", concatenated_string)

# Check if a substring exists
contains_e = np.char.find(string_array, 'e') != -1
print("Contains 'e' array:", contains_e)

# Replace a substring
replaced_array = np.char.replace(string_array, 'a', 'x')
print("Replaced 'a' with 'x':", replaced_array)


First element: apple
Slice of elements: ['banana' 'cherry']
Uppercase array: ['APPLE' 'BANANA' 'CHERRY' 'DATE']
Concatenated array: ['apple_fruit' 'banana_fruit' 'cherry_fruit' 'date_fruit']
Contains 'e' array: [ True False  True  True]
Replaced 'a' with 'x': ['xpple' 'bxnxnx' 'cherry' 'dxte']
