<a href="https://colab.research.google.com/github/saranyareddy77/MDS-LAB/blob/main/WEEK-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Array Manipulations and Random Functions - Precise Control

In [1]:
import numpy as np

### 1. Random Functions

In [2]:
# Generate a single random float
float1 = np.random.rand()
print("Single Random Float:", float1)

Single Random Float: 0.5357270786679222


In [3]:
# Generate a 1D array of 5 random floats
arr1 = np.random.rand(5)
print("1D Array of Random Floats:\n", arr1)

1D Array of Random Floats:
 [0.1834546  0.02071773 0.89531029 0.89185719 0.80320544]


In [4]:
# Generate a 2D array (2 rows, 3 columns) of random floats
arr2 = np.random.rand(2, 3)
print("2D Array of Random Floats (2x3):\n", arr2)

2D Array of Random Floats (2x3):
 [[0.50971137 0.02299755 0.4053481 ]
 [0.18963809 0.59032199 0.73591853]]


In [5]:
# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
int1 = np.random.randint(10)
print("Single Random Integer (0-9):", int1)

Single Random Integer (0-9): 2


In [6]:
# Generate a 1D array of 7 random integers between 1 and 100 (inclusive)
arr3 = np.random.randint(1, 101, size=7)
print("1D Array of Random Integers (1-100):\n", arr3)

1D Array of Random Integers (1-100):
 [ 70  56 100  79  83  79  96]


In [7]:
# Array for shuffling, first element 100
arr_shuf1 = np.array([100, 20, 30, 40, 50, 60])
print("Original 1D Array for Shuffling:", arr_shuf1)

Original 1D Array for Shuffling: [100  20  30  40  50  60]


In [8]:
# Perform in-place shuffling
np.random.shuffle(arr_shuf1)
print("Shuffled 1D Array:\n", arr_shuf1)

Shuffled 1D Array:
 [100  60  30  20  50  40]


In [9]:
# Array for random choices, first element 100
arr_choice1 = np.array([100, 5, 10, 15, 20, 25])
print("Original 1D Array for Choices:", arr_choice1)

Original 1D Array for Choices: [100   5  10  15  20  25]


In [10]:
# Choose 3 random elements with replacement from arr_choice1
choice1 = np.random.choice(arr_choice1, 3)
print("Random Choice (with replacement):", choice1)

Random Choice (with replacement): [10 10  5]


In [11]:
# Choose 3 random elements without replacement from arr_choice1
choice2 = np.random.choice(arr_choice1, 3, replace=False)
print("Random Choice (without replacement):", choice2)

Random Choice (without replacement): [  5  25 100]


### 2. Manipulation of NumPy Arrays: Indexing

In [12]:
# 1D Array for indexing, first element 100
arr1d1 = np.array([100, 201, 301, 401, 501, 601, 701, 801, 901, 1001])
print("1D Array for Indexing:", arr1d1)

1D Array for Indexing: [ 100  201  301  401  501  601  701  801  901 1001]


In [13]:
# Access element at index 0
val1 = arr1d1[0]
print("Element at index 0:", val1)

Element at index 0: 100


In [14]:
# Access element at index 4
val2 = arr1d1[4]
print("Element at index 4:", val2)

Element at index 4: 501


In [15]:
# Access the last element using negative indexing
val3 = arr1d1[-1]
print("Last element:", val3)

Last element: 1001


In [16]:
# 2D Array for indexing, first element 100
arr2d1 = np.array([[100, 202, 302], [402, 502, 602], [702, 802, 902]])
print("\n2D Array for Indexing:\n", arr2d1)


2D Array for Indexing:
 [[100 202 302]
 [402 502 602]
 [702 802 902]]


In [17]:
# Access element at row 0, column 0
val4 = arr2d1[0, 0]
print("Element at (0,0):", val4)

Element at (0,0): 100


In [18]:
# Access element at row 1, column 2
val5 = arr2d1[1, 2]
print("Element at (1,2):", val5)

Element at (1,2): 602


In [19]:
# Access the entire first row
row1 = arr2d1[0]
print("First row:\n", row1)

First row:
 [100 202 302]


### 2. Manipulation of NumPy Arrays: Slicing

In [20]:
# 1D Array for slicing, first element 100
arr1d2 = np.array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])
print("1D Array for Slicing:", arr1d2)

1D Array for Slicing: [100 110 120 130 140 150 160 170 180 190]


In [21]:
# Slice elements from index 1 to 5 (exclusive)
slice1 = arr1d2[1:5]
print("Elements from index 1 to 4:", slice1)

Elements from index 1 to 4: [110 120 130 140]


In [22]:
# Slice elements from beginning up to index 3 (exclusive)
slice2 = arr1d2[:3]
print("Elements from start to index 2:", slice2)

Elements from start to index 2: [100 110 120]


In [23]:
# Slice elements from index 6 to the end
slice3 = arr1d2[6:]
print("Elements from index 6 to end:", slice3)

Elements from index 6 to end: [160 170 180 190]


In [24]:
# Slice every other element
slice4 = arr1d2[::2]
print("Every other element:", slice4)

Every other element: [100 120 140 160 180]


In [25]:
# 2D Array for slicing, first element 100
arr2d2 = np.array([[100, 111, 121, 131], [141, 151, 161, 171], [181, 191, 201, 211]])
print("\n2D Array for Slicing:\n", arr2d2)


2D Array for Slicing:
 [[100 111 121 131]
 [141 151 161 171]
 [181 191 201 211]]


In [26]:
# Slice the first two rows and all columns
slice5 = arr2d2[:2, :]
print("First two rows, all columns:\n", slice5)

First two rows, all columns:
 [[100 111 121 131]
 [141 151 161 171]]


In [27]:
# Slice all rows and the last two columns
slice6 = arr2d2[:, 2:]
print("All rows, last two columns:\n", slice6)

All rows, last two columns:
 [[121 131]
 [161 171]
 [201 211]]


In [28]:
# Slice a sub-grid: rows 0-1, columns 1-2
slice7 = arr2d2[0:2, 1:3]
print("Sub-grid (rows 0-1, cols 1-2):\n", slice7)

Sub-grid (rows 0-1, cols 1-2):
 [[111 121]
 [151 161]]


### 2. Manipulation of NumPy Arrays: Reshaping

In [29]:
# 1D Array for reshaping, first element 100
arr1d3 = np.array([100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print("1D Array for Reshaping:", arr1d3)

1D Array for Reshaping: [100   1   2   3   4   5   6   7   8   9  10  11]


In [30]:
# Reshape arr1d3 to a 3x4 2D array
reshaped1 = arr1d3.reshape(3, 4)
print("Reshaped 1D to 3x4 2D array:\n", reshaped1)

Reshaped 1D to 3x4 2D array:
 [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [31]:
# 2D Array for reshaping, first element 100
arr2d3 = np.array([[100, 21, 31], [41, 51, 61], [71, 81, 91]])
print("\n2D Array for Reshaping:\n", arr2d3)


2D Array for Reshaping:
 [[100  21  31]
 [ 41  51  61]
 [ 71  81  91]]


In [32]:
# Reshape arr2d3 to a 1x9 2D array
reshaped2 = arr2d3.reshape(1, 9)
print("Reshaped 2D to 1x9 2D array:\n", reshaped2)

Reshaped 2D to 1x9 2D array:
 [[100  21  31  41  51  61  71  81  91]]


In [33]:
# Flatten arr2d3 to a 1D array using ravel()
flat1 = arr2d3.ravel()
print("Flattened (ravel) 2D to 1D array:\n", flat1)

Flattened (ravel) 2D to 1D array:
 [100  21  31  41  51  61  71  81  91]


In [34]:
# Flatten arr2d3 to a 1D array using flatten()
flat2 = arr2d3.flatten()
print("Flattened (flatten) 2D to 1D array:\n", flat2)

Flattened (flatten) 2D to 1D array:
 [100  21  31  41  51  61  71  81  91]


### 2. Manipulation of NumPy Arrays: Joining

In [35]:
# First 1D array for joining, first element 100
arr_join1 = np.array([100, 2, 3, 4])
print("First 1D Array for Joining:", arr_join1)

First 1D Array for Joining: [100   2   3   4]


In [36]:
# Second 1D array for joining
arr_join2 = np.array([5, 6, 7, 8])
print("Second 1D Array for Joining:", arr_join2)

Second 1D Array for Joining: [5 6 7 8]


In [37]:
# Concatenate 1D arrays
joined1 = np.concatenate((arr_join1, arr_join2))
print("Concatenated 1D Arrays:\n", joined1)

Concatenated 1D Arrays:
 [100   2   3   4   5   6   7   8]


In [38]:
# First 2D array for joining, first element 100
arr_join3 = np.array([[100, 22, 32], [42, 52, 62]])
print("\nFirst 2D Array for Joining:\n", arr_join3)


First 2D Array for Joining:
 [[100  22  32]
 [ 42  52  62]]


In [39]:
# Second 2D array for joining
arr_join4 = np.array([[72, 82, 92], [12, 22, 32]])
print("Second 2D Array for Joining:\n", arr_join4)

Second 2D Array for Joining:
 [[72 82 92]
 [12 22 32]]


In [40]:
# Join 2D arrays vertically using vstack
joined2 = np.vstack((arr_join3, arr_join4))
print("Vertically Stacked 2D Arrays:\n", joined2)

Vertically Stacked 2D Arrays:
 [[100  22  32]
 [ 42  52  62]
 [ 72  82  92]
 [ 12  22  32]]


In [41]:
# Join 2D arrays horizontally using hstack
joined3 = np.hstack((arr_join3, arr_join4))
print("\nHorizontally Stacked 2D Arrays:\n", joined3)


Horizontally Stacked 2D Arrays:
 [[100  22  32  72  82  92]
 [ 42  52  62  12  22  32]]


### 2. Manipulation of NumPy Arrays: Splitting

In [42]:
# 1D Array for splitting, first element 100
arr1d4 = np.array([100, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print("1D Array for Splitting:", arr1d4)

1D Array for Splitting: [100  11  12  13  14  15  16  17  18  19]


In [43]:
# Split arr1d4 into two parts at index 5
split1_part1, split1_part2 = np.split(arr1d4, [5])
print("First part of 1D split:\n", split1_part1)

First part of 1D split:
 [100  11  12  13  14]


In [44]:
# Print the second part of the 1D split
print("Second part of 1D split:\n", split1_part2)

Second part of 1D split:
 [15 16 17 18 19]


In [45]:
# 2D Array for splitting, first element 100
arr2d4 = np.array([[100, 23, 33], [43, 53, 63], [73, 83, 93], [13, 23, 33]])
print("\n2D Array for Splitting:\n", arr2d4)


2D Array for Splitting:
 [[100  23  33]
 [ 43  53  63]
 [ 73  83  93]
 [ 13  23  33]]


In [46]:
# Split arr2d4 vertically into two parts after row 2
split2_part1, split2_part2 = np.vsplit(arr2d4, [2])
print("First part of 2D vertical split:\n", split2_part1)

First part of 2D vertical split:
 [[100  23  33]
 [ 43  53  63]]


In [47]:
# Print the second part of the 2D vertical split
print("Second part of 2D vertical split:\n", split2_part2)

Second part of 2D vertical split:
 [[73 83 93]
 [13 23 33]]


In [48]:
# Split arr2d4 horizontally into two parts after column 1
split3_part1, split3_part2 = np.hsplit(arr2d4, [1])
print("\nFirst part of 2D horizontal split:\n", split3_part1)


First part of 2D horizontal split:
 [[100]
 [ 43]
 [ 73]
 [ 13]]


In [49]:
# Print the second part of the 2D horizontal split
print("Second part of 2D horizontal split:\n", split3_part2)

Second part of 2D horizontal split:
 [[23 33]
 [53 63]
 [83 93]
 [23 33]]


### 3. Computation on NumPy Arrays: Universal Functions (Ufuncs)

In [50]:
# 1D Array for Ufuncs, first element 100
arr1d5 = np.array([100, 4, 9, 16, 25, 36])
print("1D Array for Ufuncs:", arr1d5)

1D Array for Ufuncs: [100   4   9  16  25  36]


In [51]:
# Apply square root ufunc to arr1d5
ufunc1 = np.sqrt(arr1d5)
print("Square root of 1D array:\n", ufunc1)

Square root of 1D array:
 [10.  2.  3.  4.  5.  6.]


In [52]:
# Apply exponential ufunc to first 3 elements of arr1d5
ufunc2 = np.exp(arr1d5[:3]) # Limiting output for clarity
print("Exponential of first 3 elements of 1D array:\n", ufunc2)

Exponential of first 3 elements of 1D array:
 [2.68811714e+43 5.45981500e+01 8.10308393e+03]


In [53]:
# Apply sine ufunc to arr1d5
ufunc3 = np.sin(arr1d5)
print("Sine of 1D array:\n", ufunc3)

Sine of 1D array:
 [-0.50636564 -0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]


In [54]:
# 2D Array for Ufuncs, first element 100
arr2d5 = np.array([[100, 0, np.pi/2], [np.pi, 2*np.pi, -3*np.pi/2]])
print("\n2D Array for Ufuncs:\n", arr2d5)


2D Array for Ufuncs:
 [[100.           0.           1.57079633]
 [  3.14159265   6.28318531  -4.71238898]]


In [55]:
# Apply sine ufunc to arr2d5
ufunc4 = np.sin(arr2d5)
print("Sine of 2D array:\n", ufunc4)

Sine of 2D array:
 [[-5.06365641e-01  0.00000000e+00  1.00000000e+00]
 [ 1.22464680e-16 -2.44929360e-16  1.00000000e+00]]


In [56]:
# Apply absolute value ufunc to (arr2d5 - 50)
ufunc5 = np.abs(arr2d5 - 50)
print("Absolute values of (arr2d5 - 50):\n", ufunc5)

Absolute values of (arr2d5 - 50):
 [[50.         50.         48.42920367]
 [46.85840735 43.71681469 54.71238898]]


In [57]:
# Apply floor ufunc to arr2d5
ufunc6 = np.floor(arr2d5)
print("Floor of 2D array:\n", ufunc6)

Floor of 2D array:
 [[100.   0.   1.]
 [  3.   6.  -5.]]


### 3. Computation on NumPy Arrays: Mathematical Methods

In [58]:
# 1D Array for Math Methods, first element 100
arr1d6 = np.array([100, 5, 10, 15, 20])
print("1D Array for Math Methods:", arr1d6)

1D Array for Math Methods: [100   5  10  15  20]


In [59]:
# Calculate the sum of all elements in arr1d6
math1 = arr1d6.sum()
print("Sum of 1D array:", math1)

Sum of 1D array: 150


In [60]:
# Calculate the mean of all elements in arr1d6
math2 = arr1d6.mean()
print("Mean of 1D array:", math2)

Mean of 1D array: 30.0


In [61]:
# Find the maximum value in arr1d6
math3 = arr1d6.max()
print("Max value in 1D array:", math3)

Max value in 1D array: 100


In [62]:
# Find the minimum value in arr1d6
math4 = arr1d6.min()
print("Min value in 1D array:", math4)

Min value in 1D array: 5


In [63]:
# Calculate the standard deviation of arr1d6
math5 = arr1d6.std()
print("Standard deviation of 1D array:", math5)

Standard deviation of 1D array: 35.35533905932738


In [64]:
# 2D Array for Math Methods, first element 100
arr2d6 = np.array([[100, 24, 34], [44, 54, 64], [74, 84, 94]])
print("\n2D Array for Math Methods:\n", arr2d6)


2D Array for Math Methods:
 [[100  24  34]
 [ 44  54  64]
 [ 74  84  94]]


In [65]:
# Calculate the sum of all elements in arr2d6
math6 = arr2d6.sum()
print("Sum of all elements in 2D array:", math6)

Sum of all elements in 2D array: 572


In [66]:
# Calculate the mean of all elements in arr2d6
math7 = arr2d6.mean()
print("Mean of all elements in 2D array:", math7)

Mean of all elements in 2D array: 63.55555555555556


In [67]:
# Calculate the sum along columns (axis=0) in arr2d6
math8 = arr2d6.sum(axis=0)
print("Sum along columns (axis=0) in 2D array:\n", math8)

Sum along columns (axis=0) in 2D array:
 [218 162 192]


In [68]:
# Calculate the mean along rows (axis=1) in arr2d6
math9 = arr2d6.mean(axis=1)
print("Mean along rows (axis=1) in 2D array:\n", math9)

Mean along rows (axis=1) in 2D array:
 [52.66666667 54.         84.        ]


In [69]:
# Find the minimum value in arr2d6
math10 = arr2d6.min()
print("Minimum value in 2D array:", math10)

Minimum value in 2D array: 24


In [70]:
# Find the maximum value along columns (axis=0) in arr2d6
math11 = arr2d6.max(axis=0)
print("Maximum value along columns (axis=0) in 2D array:\n", math11)

Maximum value along columns (axis=0) in 2D array:
 [100  84  94]
